#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: TasmoAdmin
# Ensures data is store in a persistent location
# ==============================================================================
# shellcheck disable=SC1091
#source /usr/lib/hassio-addons/base.sh


restore_nginx_conf() {
  local config_path="$1"
  local config_template="$2"
  local backup_path="${config_path}.invalid.$(date +%s)"

  if [ -f "$config_path" ]; then
    cp -v "$config_path" "$backup_path"
  fi

  if [ -f "$config_template" ]; then
    cp -v "$config_template" "$config_path"
  elif [ -f /etc/nginx/nginx.conf.org ]; then
    cp -v /etc/nginx/nginx.conf.org "$config_path"
  fi
}

validate_nginx_conf() {
  local config_path="$1"
  local config_template="$2"

  if ! nginx -t -q -c "$config_path"; then
    echo "Invalid nginx config at ${config_path}, restoring default config..."
    restore_nginx_conf "$config_path" "$config_template"
  fi
}

# Setup structure if it does not exists
if [ ! -d "/data/nginx" ]; then
  echo 'Data nginx directory not initialized, doing that now...'
  mkdir -p /data/nginx/certs
  cp -v /etc/nginx/mime.types /data/nginx/mime.types
  cp -Rv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
  cp -Rv /etc/nginx/nginx.conf.org /data/nginx/nginx.conf.org
  cp -Rv /data/nginx/nginx.conf.org /data/nginx/nginx.conf
  cp -Rv /etc/nginx/nginx-ssl.conf /data/nginx/nginx-ssl.conf
  cp -Rv /etc/nginx/certs/* /data/nginx/certs
fi


if [ ! -f "/data/nginx/mime.types" ]; then
  echo 'Copying missing mime.types into persistent nginx directory...'
  cp -v /etc/nginx/mime.types /data/nginx/mime.types
fi

if [[ -L "/data/nginx/nginx.conf" ]]; then
  echo "ERROR: /data/nginx/nginx.conf is a symlink, try to download the default nginx.conf from github";
  rm -rf /data/nginx/nginx.conf
  wget -O /data/nginx/nginx.conf https://raw.githubusercontent.com/TasmoAdmin/TasmoAdmin/master/.docker/rootfs/etc/nginx/nginx.conf
  cp -Rv /data/nginx/nginx.conf /etc/nginx/nginx.conf.org
fi

validate_nginx_conf /data/nginx/nginx.conf /data/nginx/nginx.conf.org

echo 'Symlinking /etc/nginx.conf from persistent storage location...'
rm -rf /etc/nginx/nginx.conf
ln -s /data/nginx/nginx.conf /etc/nginx/nginx.conf

declare certfile
declare keyfile

if ${SSL}; then
    validate_nginx_conf /data/nginx/nginx-ssl.conf /etc/nginx/nginx-ssl.conf
    echo 'Symlinking /etc/nginx.conf to nginx-ssl.config on persistent storage...'
    rm -f -r /etc/nginx/nginx.conf
    ln -s /data/nginx/nginx-ssl.conf /etc/nginx/nginx.conf
    rm -f -r /etc/nginx/certs
    echo 'Symlinking /etc/nginx/certs to persistent storage...'
    ln -s /data/nginx/certs /etc/nginx/certs
fi
